version: 0.0
os: linux
files:
   - source: target/test.war
     destination: /home/ubuntu/deploy/
hooks:
  BeforeInstall:
    - location: scripts/beforeinstall.sh
      timeout: 120
      runas: root
  AfterInstall:
    - location: scripts/afterInstall.sh
      timeout: 60
      runas: root

